# Generated by Django 6.0.7 on 2026-08-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
